# Generated by Django 5.2 on 2025-06-03 08:00

import common.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cycle_number', models.PositiveIntegerField(verbose_name='주기 번호')),
                ('cycle_start', models.DateField(verbose_name='처방일')),
                ('cycle_end', models.DateField(blank=True, null=True, verbose_name='다음 방문 예정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '복약 주기',
                'verbose_name_plural': '복약 주기들',
                'db_table': 'medication_cycles',
                'ordering': ['-cycle_start'],
            },
        ),
        migrations.CreateModel(
            name='MedicationGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('group_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='복약그룹 코드')),
                ('group_name', models.CharField(help_text='예: 아침약, 바르는약, 혈압약 등', max_length=50, verbose_name='복약그룹명')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='알림 설정')),
            ],
            options={
                'verbose_name': '복약그룹',
                'verbose_name_plural': '복약그룹들',
                'db_table': 'medication_groups',
            },
            bases=(models.Model, common.models.base_model.CodeGeneratorMixin),
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('record_type', models.CharField(choices=[('TAKEN', '복용함'), ('MISSED', '복용 누락'), ('SIDE_EFFECT', '부작용'), ('SKIPPED', '의도적 건너뜀'), ('NOTE', '메모')], default='TAKEN', max_length=15, verbose_name='기록 유형')),
                ('record_date', models.DateTimeField(verbose_name='기록 일시')),
                ('quantity_taken', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='복용량')),
                ('notes', models.TextField(blank=True, verbose_name='기록 내용')),
            ],
            options={
                'verbose_name': '복약 기록',
                'verbose_name_plural': '복약 기록들',
                'db_table': 'medication_records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('prescription_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='처방전 코드')),
                ('prescription_date', models.DateField(verbose_name='처방일/내원일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '처방전',
                'verbose_name_plural': '처방전들',
                'db_table': 'prescriptions',
            },
            bases=(models.Model, common.models.base_model.CodeGeneratorMixin),
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('standard_dosage_pattern', models.JSONField(default=list, help_text='["D", "A", "E", "N", "P"] - 아침/점심/저녁/취침전/필요시(["시간대":"복용량"] 리스트)', verbose_name='복약 처방')),
                ('duration_days', models.IntegerField(verbose_name='처방일수')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 처방량(1회 용량*복약 빈도*복약 개수*복약 단위?)')),
            ],
            options={
                'verbose_name': '처방 의약품',
                'verbose_name_plural': '처방 의약품들',
                'db_table': 'prescription_medications',
            },
        ),
        migrations.CreateModel(
            name='MedicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('actual_dosage_pattern', models.JSONField(blank=True, help_text='템플릿과 다른 경우에만 저장', null=True)),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='잔여량')),
                ('patient_adjustments', models.JSONField(default=dict, help_text='환자별 용량 조정, 복용 시간 변경 등')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_details', to='bokyak.medicationcycle', verbose_name='복약 주기')),
            ],
            options={
                'verbose_name': '복약 상세',
                'verbose_name_plural': '복약 상세들',
                'db_table': 'medication_details',
            },
        ),
        migrations.CreateModel(
            name='MedicationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('alert_type', models.CharField(choices=[('DOSAGE', '복용 알림'), ('REFILL', '처방전 갱신 알림'), ('APPOINTMENT', '진료 예약 알림')], max_length=15, verbose_name='알림 유형')),
                ('alert_time', models.TimeField(verbose_name='알림 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='알림 활성화')),
                ('message', models.TextField(blank=True, verbose_name='알림 메시지')),
                ('medication_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bokyak.medicationdetail', verbose_name='복약 상세')),
            ],
            options={
                'verbose_name': '복약 알림',
                'verbose_name_plural': '복약 알림들',
                'db_table': 'medication_alerts',
            },
        ),
    ]
