# Generated by Django 5.2 on 2025-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bokyak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField()),
                ('cycle_id', models.IntegerField()),
                ('rel_ill', models.CharField(null=True)),
                ('item_seq', models.IntegerField()),
                ('med_term', models.CharField(null=True)),
                ('per_term', models.IntegerField()),
                ('per_num', models.IntegerField(default=0)),
                ('med_total', models.IntegerField()),
            ],
            options={
                'db_table': 'bokyak_detail',
            },
        ),
        migrations.CreateModel(
            name='BokyakCycle',
            fields=[
                ('group_id', models.CharField()),
                ('cycle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rel_hosp', models.CharField(null=True)),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'bokyak_cycle',
            },
        ),
        migrations.CreateModel(
            name='BokyakGroup',
            fields=[
                ('user_id', models.CharField()),
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
                ('rel_hosp', models.CharField(null=True)),
                ('rel_ill', models.CharField(null=True)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bokyak_group',
            },
        ),
        migrations.CreateModel(
            name='BokyakRecord',
            fields=[
                ('group_id', models.CharField()),
                ('cycle_id', models.IntegerField(default='10000000')),
                ('record_id', models.IntegerField(default='10000000', primary_key=True, serialize=False)),
                ('rel_ill', models.CharField(null=True)),
                ('rel_item', models.CharField()),
                ('rec_date', models.DateTimeField()),
                ('reg_date', models.DateTimeField()),
                ('record', models.CharField()),
            ],
            options={
                'db_table': 'bokyak_record',
            },
        ),
    ]
