# Generated by Django 5.2 on 2025-05-18 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BokyakCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.IntegerField(blank=True, default=10000, null=True)),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField(null=True)),
                ('rel_hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', to_field='hosp_info')),
            ],
            options={
                'db_table': 'bokyak_cycle',
            },
        ),
        migrations.CreateModel(
            name='Bokyak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_term', models.CharField(default='D')),
                ('per_term', models.IntegerField()),
                ('per_num', models.IntegerField(default=0)),
                ('med_total', models.IntegerField()),
                ('rel_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokyak', to='user.medinfo')),
                ('rel_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokyak', to='bokyak.bokyakcycle')),
            ],
            options={
                'db_table': 'bokyak_detail',
            },
        ),
        migrations.CreateModel(
            name='BokyakGroup',
            fields=[
                ('group_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('group_info', models.ManyToManyField(related_name='bokyak_group', to='user.userinfo')),
            ],
            options={
                'db_table': 'bokyak_group',
            },
        ),
        migrations.AddField(
            model_name='bokyakcycle',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokyak.bokyakgroup'),
        ),
        migrations.CreateModel(
            name='BokyakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateTimeField()),
                ('reg_date', models.DateTimeField()),
                ('record', models.CharField()),
                ('rel_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokyak_record', to='bokyak.bokyakcycle')),
                ('rel_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokyak_record', to='user.medinfo')),
            ],
            options={
                'db_table': 'bokyak_record',
            },
        ),
        migrations.AddConstraint(
            model_name='bokyakcycle',
            constraint=models.UniqueConstraint(fields=('group_id', 'cycle_id'), name='unique_user_group_cycle'),
        ),
    ]
