# Generated by Django 5.2 on 2025-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokyak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokyak',
            name='med_term',
            field=models.CharField(choices=[('H', '시간'), ('D', '하루'), ('W', '한주'), ('P', '필요시')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='bokyak',
            name='med_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bokyak',
            name='per_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bokyak',
            name='per_term',
            field=models.IntegerField(default=1),
        ),
    ]
