# Generated by Django 4.2.22 on 2025-06-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bokyak", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionmedication",
            name="medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescribed_medications",
                to="user.medication",
                verbose_name="의약품 정보",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionmedication",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescribed_medications",
                to="bokyak.prescription",
                verbose_name="처방전",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionmedication",
            name="source_prescription",
            field=models.ForeignKey(
                blank=True,
                help_text="원본 처방전",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_medications",
                to="bokyak.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="previous_prescription",
            field=models.ForeignKey(
                blank=True,
                help_text="갱신된 경우 이전 처방전 참조",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_prescriptions",
                to="bokyak.prescription",
                verbose_name="이전 처방전",
            ),
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="medication_detail",
            field=models.ForeignKey(
                help_text="복약 상세",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_records",
                to="bokyak.medicationdetail",
            ),
        ),
        migrations.AddField(
            model_name="medicationgroup",
            name="medical_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_medical_info",
                to="user.usermedicalinfo",
                verbose_name="의료 정보",
            ),
        ),
        migrations.AddField(
            model_name="medicationdetail",
            name="group",
            field=models.ForeignKey(
                help_text="복약 그룹",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medication_details",
                to="bokyak.medicationgroup",
            ),
        ),
        migrations.AddField(
            model_name="medicationdetail",
            name="prescription_medication",
            field=models.ForeignKey(
                help_text="처방약",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medication_details",
                to="bokyak.prescriptionmedication",
            ),
        ),
        migrations.AddField(
            model_name="medicationalert",
            name="medication_detail",
            field=models.ForeignKey(
                help_text="복약 상세",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_alerts",
                to="bokyak.medicationdetail",
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionmedication",
            index=models.Index(
                fields=["prescription"], name="idx_presc_med_prescription"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionmedication",
            index=models.Index(fields=["medication"], name="idx_presc_med_medication"),
        ),
        migrations.AlterUniqueTogether(
            name="prescriptionmedication",
            unique_together={("prescription", "medication")},
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_date"], name="idx_prescription_date"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["is_active"], name="idx_prescription_active"),
        ),
        migrations.AddIndex(
            model_name="medicationrecord",
            index=models.Index(
                fields=["medication_detail", "record_date"],
                name="idx_med_record_user_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationdetail",
            constraint=models.UniqueConstraint(
                fields=("group", "prescription_medication"),
                name="unique_group_medication",
            ),
        ),
    ]
