# Generated by Django 5.2 on 2025-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField()),
                ('hosp_name', models.CharField(max_length=100)),
                ('hosp_id', models.CharField(max_length=10)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField()),
                ('ill_type', models.CharField(max_length=1)),
                ('ill_id', models.CharField(max_length=10)),
                ('ill_name', models.CharField(max_length=100)),
                ('ill_start', models.DateField(null=True)),
                ('ill_end', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'illness',
            },
        ),
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_code', models.CharField(max_length=9)),
                ('main_ingr_item', models.CharField(max_length=100)),
                ('main_ingr_den', models.FloatField()),
                ('main_ingr_unit', models.CharField()),
            ],
            options={
                'db_table': 'main_ingredient',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('item_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('main_item_ingr', models.CharField()),
                ('main_ingr_eng', models.CharField()),
                ('entp_name', models.CharField()),
                ('item_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('join_date', models.DateTimeField()),
                ('push_agree', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
