# Generated by Django 5.2 on 2025-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='ill_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='illness',
            name='ill_type',
            field=models.CharField(choices=[('D', '질병'), ('S', '증상')], default='D', max_length=1),
        ),
    ]
