# Generated by Django 4.2.22 on 2025-06-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medication",
            old_name="main_ingredients",
            new_name="ingredients",
        ),
        migrations.AlterField(
            model_name="medicationingredient",
            name="main_ingredient",
            field=models.ForeignKey(
                help_text="성분",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medication_ingredients",
                to="user.mainingredient",
            ),
        ),
        migrations.AlterField(
            model_name="medicationingredient",
            name="medication",
            field=models.ForeignKey(
                help_text="약물",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_ingredients",
                to="user.medication",
            ),
        ),
    ]
