# Generated by Django 4.2.22 on 2025-06-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_main_ingredients_medication_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainingredient",
            options={
                "ordering": ["main_ingr_name_kr", "main_ingr_name_en"],
                "verbose_name": "주성분",
                "verbose_name_plural": "주성분들",
            },
        ),
        migrations.RemoveIndex(
            model_name="mainingredient",
            name="idx_main_ingr_orig_code",
        ),
        migrations.RemoveIndex(
            model_name="mainingredient",
            name="idx_main_ingr_class",
        ),
        migrations.RenameField(
            model_name="mainingredient",
            old_name="main_ingr_density",
            new_name="density",
        ),
        migrations.RenameField(
            model_name="mainingredient",
            old_name="main_ingr_unit",
            new_name="unit",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="classification",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="data_quality_score",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="dosage_form",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="dosage_form_code",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="original_code",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="original_density_notation",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="route",
        ),
        migrations.AddField(
            model_name="mainingredient",
            name="atc_code",
            field=models.CharField(
                blank=True, help_text="act 코드", max_length=50, verbose_name="제형"
            ),
        ),
        migrations.AlterField(
            model_name="mainingredient",
            name="ingr_code",
            field=models.CharField(
                help_text="일반명코드",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="성분 고유 코드",
            ),
        ),
    ]
