# Generated by Django 5.2 on 2025-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_illness_ill_id_alter_illness_ill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_id',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_type',
            field=models.CharField(default=''),
        ),
    ]
