# Generated by Django 5.2 on 2025-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_hospital_doctor_name_alter_hospital_hosp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctor_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
