# Generated by Django 4.2.22 on 2025-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_mainingredient_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mainingredient",
            name="idx_main_ingr_status",
        ),
        migrations.RemoveField(
            model_name="mainingredient",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="mainingredient",
            name="atc_code",
            field=models.CharField(
                blank=True, help_text="ATC 코드", max_length=50, verbose_name="ATC 코드"
            ),
        ),
    ]
