# Generated by Django 4.2.22 on 2025-06-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_mainingredient_idx_main_ingr_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ayakuser",
            name="user_name",
        ),
        migrations.AddField(
            model_name="ayakuser",
            name="user_nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="사용자 닉네임"
            ),
        ),
        migrations.AlterField(
            model_name="ayakuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="활성상태"),
        ),
        migrations.AlterField(
            model_name="ayakuser",
            name="join_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="가입일자"),
        ),
        migrations.AlterField(
            model_name="ayakuser",
            name="push_agree",
            field=models.BooleanField(default=False, verbose_name="푸시알림 동의"),
        ),
        migrations.AlterField(
            model_name="ayakuser",
            name="user_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="사용자 아이디",
            ),
        ),
    ]
