# Generated by Django 4.2.22 on 2025-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_ayakuser_user_name_ayakuser_user_nickname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ayakuser",
            name="user_nickname",
        ),
        migrations.AddField(
            model_name="ayakuser",
            name="user_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="사용자 이름"
            ),
        ),
    ]
