# Generated by Django 5.2 on 2025-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_illness_ill_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='ill_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
