# Generated by Django 4.2.22 on 2025-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_ayakuser_user_nickname_ayakuser_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayakuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성상태"),
        ),
    ]
